Hemophilia/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Rehabilitation.urls', 'Rehabilitation'), namespace='Rehabilitation')),
    path('summernote/', include('django_summernote.urls'), name='summernote'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Rehabilitation/urls.py
# -*- coding: utf-8 -*-
# Author:RicardoM

from django.urls import path

from Rehabilitation import views

urlpatterns = [

    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('article/<int:articleId>', views.article, name='article'),
    path('write/', views.write, name='write'),
    path('userProfile/<str:username>', views.UserProfile.as_view(), name='userProfile'),
    path('operateArticle', views.OperateArticle.as_view(), name='operateArticle'),
    path('messages/', views.messages, name='messages'),
    path('sendMessage/', views.sendMessage, name='sendMessage'),
    path('deleteConversation/', views.delete_conversation, name='deleteConversation'),
    path('modifyUser/', views.modify_profile, name='modifyProfile'),
    path('shieldUser/<str:convId>', views.shield_user, name='shieldUser'),
    path('test/', views.test),
    path('conversation/<str:convId>', views.conversation, name='conversation'),
    path('comment', views.comment, name='comment'),
    path('userPic/', views.UserPic.as_view(), name='userPic'),
    path('', views.index, name='index'),

]

Rehabilitation/views.py
import json
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.views.generic.base import View
from django.db.models import Q
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.template.loader import render_to_string
from django.utils import timezone
from Rehabilitation import form
from PIL import Image
from .models import *
from io import BytesIO


def index(request):
    article_list = Article.objects.filter(status="published")
    return render(request, 'Rehabilitation/index.html', locals())


class Register(View):

    @staticmethod
    def post(request):
        r = User()
        r.username = request.POST['username']
        r.password = request.POST['password']
        r.realname = request.POST.get('realname', '')
        r.nickname = request.POST.get('nickname', r.username)
        r.gender = request.POST.get('gender', '')
        r.phone = request.POST.get('phone', '')
        r.email = request.POST.get('email', '')
        res = {
            'status': '',
            'errorMsg': '',
        }
        # 判断用户名是否存在
        if User.objects.filter(username=r.username):
            res['status'] = '0'
            res['errorMsg'] = '该用户名已经存在，请重新输入!'
        else:
            res['status'] = '1'
            r.password = make_password(r.password)
            r.save()
        return HttpResponse(json.dumps(res, ensure_ascii=False), content_type='application/json')


class Login(View):

    @staticmethod
    def post(request):
        res = {}
        u = User()
        u.username = request.POST['username']
        u.password = request.POST['password']
        u.remember_me = request.POST.get('remember_me', 'true')
        user = authenticate(username=u.username, password=u.password)
        if user is None:
            res['status'] = '0'
        else:
            login(request, user)
            res['status'] = '1'
        return HttpResponse(json.dumps(res, ensure_ascii=False), content_type='application/json')


@login_required
def comment(request):
    if request.POST.get('article_id'):
        article_id = request.POST.get('article_id')
    else:
        article_id = request.GET.get('article_id')
    com = request.POST.get('comment')
    to_comment = request.POST.get('to_comment')
    new_comment = Comment()
    new_comment.user = request.user
    new_comment.article = Article.objects.filter(id=article_id)[0]
    if com:
        new_comment.comment = com
        new_comment.comment_type = '1'
    else:
        new_comment.comment_type = '2'
    if to_comment:
        new_comment.parent_comment = Comment.objects.filter(id=to_comment)[0]
    if new_comment.comment_type == '2':
        like_comment = Comment.objects.filter(comment_type="2", article=new_comment.article, user=request.user)
        print(like_comment)
        if len(like_comment) > 0:
            print(len(like_comment))
            like_comment[0].delete()
        else:
            new_comment.save()
    else:
        new_comment.save()
    return redirect(reverse('Rehabilitation:article', kwargs={'articleId': article_id}))


class Logout(View):

    @staticmethod
    @login_required
    def get(request):
        next = request.GET['next']
        logout(request)
        response = redirect(next)
        if 'username' in request.COOKIES:
            response.delete_cookie('username')
        return response


def article(request, articleId):
    art = Article.objects.filter(id=articleId)[0]
    comment_list = {}
    for comment in Comment.objects.filter(article=art, comment_type='1', parent_comment=None).order_by('date').all():
        if comment not in comment_list:
            comment_list[comment] = []
        for com in Comment.objects.filter(parent_comment=comment).order_by('date').all():
            comment_list[comment].append(com)
    for comment, comment_list1 in comment_list.items():
        comment_list1.extend(findComment(comment_list1))
    if request.user.is_authenticated:
        had_like = Comment.objects.filter(comment_type='2', user=request.user, article__id=articleId)
    return render(request, 'Rehabilitation/article.html', locals())


@login_required
def write(request):
    article_Form = form.MessageForm
    category_list = Category.objects.all()
    return render(request, 'Rehabilitation/write.html', locals())


class UserProfile(View):

    @staticmethod
    def get(request, username):
        if request.user.is_authenticated:
            current_user = request.user
        u = User.objects.filter(username=username)[0]
        print(u.avatar)
        pub_article = Article.objects.filter(author=u, status="published")
        dra_article = Article.objects.filter(author=u, status="draft")
        return render(request, 'Rehabilitation/userProfile.html', locals())

    @staticmethod
    @login_required
    def post(request):
        pass


class OperateArticle(View):

    @staticmethod
    @login_required
    def get(request):
        current_user = request.user
        article_id = request.GET.get('article_id')
        category_list = Category.objects.all()
        article = Article.objects.filter(id=article_id)[0]
        return render(request, 'Rehabilitation/reEditArticle.html', locals())

    @staticmethod
    @login_required
    def post(request):
        article_id = request.POST.get('article_id')
        article = Article()
        if article_id:
            article = Article.objects.filter(id=article_id)[0]
        article.title = request.POST['title']
        article.brief = request.POST['brief']
        article.category_id = request.POST['category']
        article.content = request.POST['article_from']
        article.status = request.POST['status']
        article.author = request.user
        article.category = Category.objects.filter(id='1')[0]
        article.priority = 1
        if article.status == 'published':
            article.pub_date = timezone.now()
        else:
            article.status = 'draft'
        article.last_modify = timezone.now()
        article.save()
        return redirect(reverse('Rehabilitation:article', kwargs={'articleId': article.id}))


@login_required
def messages(request):
    send_user = request.user
    accept_user_id = request.GET.get('user_id')
    if accept_user_id:
        accept_user = User.objects.filter(username=accept_user_id)[0]
        isShield = Blacklist.objects.filter(master_user=send_user, black_user=accept_user)
        if len(isShield) > 0:
            isShield[0].delete()
        a = Conversation.objects.filter(send_user=send_user, accept_user=accept_user)
        b = Conversation.objects.filter(send_user=accept_user, accept_user=send_user)
        conv = None
        if len(a) > 0:
            conv = a[0]
            conv.is_delete_by_sendPeople = False
        elif len(b) > 0:
            conv = b[0]
            conv.is_delete_by_acceptPeople = False
        else:
            conv = Conversation.objects.create(send_user=send_user, accept_user=accept_user)
        conv.save()
        return redirect(reverse('Rehabilitation:conversation', kwargs={'convId': conv.id}))
    else:
        conversation_list = Conversation.objects.filter(
            Q(send_user=send_user, is_delete_by_sendPeople=False) | Q(accept_user=send_user,
                                                                      is_delete_by_acceptPeople=False))
        return render(request, 'Rehabilitation/messages.html', locals())


@login_required
def sendMessage(request):
    conv_id = request.POST.get('conv_id')
    conv = Conversation.objects.filter(id=conv_id)[0]
    current_user = request.user
    another_user = get_other_user(current_user, conv)
    if len(Blacklist.objects.filter(master_user=another_user, black_user=current_user)) < 1:
        message_detail = request.POST.get('message_detail')
        conv.last_send_time = timezone.now()
        conv.save()
        mess = Massage.objects.create(conversation=conv, send_user=current_user, accept_user=another_user,
                                      msg_detail=message_detail)
        channel_layer = get_channel_layer()
        async_to_sync(channel_layer.group_send)("abc%s" % another_user.id,
                                                generate_payload(current_user, mess))
        async_to_sync(channel_layer.group_send)("abc%s" % current_user.id,
                                                generate_payload(current_user, mess))
        res = dict(is_success=True)
    else:
        res = dict(is_success=False)
    return HttpResponse(json.dumps(res, ensure_ascii=False), content_type='application/json')


@login_required
def conversation(request, convId):
    current_user = request.user
    another_user = None
    conv = Conversation.objects.filter(id=convId)[0]
    if conv.send_user == current_user:
        another_user = conv.accept_user
    else:
        another_user = conv.send_user
    conv_list = Massage.objects.filter(conversation=conv)
    return render(request, 'Rehabilitation/conversation.html', locals())


@login_required
def delete_conversation(request):
    convId = request.GET.get('conv_id')
    current_user = request.user
    min_delete_conversation(convId, current_user)
    return redirect(reverse('Rehabilitation:messages'))


@login_required
def shield_user(request, convId):
    conv = Conversation.objects.filter(id=convId)[0]
    current_user = request.user
    other_user = get_other_user(current_user, conv)
    Blacklist.objects.create(master_user=current_user, black_user=other_user)
    min_delete_conversation(convId, current_user)
    return redirect(reverse('Rehabilitation:messages'))


def min_delete_conversation(convId, current_user):
    conv = Conversation.objects.filter(id=convId)[0]

templates/Rehabilitation/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="/static/img/Hemophilia.png">
    <link rel="stylesheet" href="/static/css/global.css">
    <link rel="stylesheet" href="/static/css/index.css">
    <link rel="stylesheet" href="/static/css/responsive.css">
    <script type="text/javascript" async="" src="/static/js/analytics.js"></script>
    <script type="text/javascript" src="/static/js/jquery.js"></script>
    <script type="text/javascript" src="/static/js/main.js"></script>
    {% block static %}{% endblock %}
    {% csrf_token %}
</head>
{% load mytags %}
<body data-mod="index" class="index-index ">
<div class="global-nav sf-header sf-header--index">
    <nav class="container nav">
        <div class="row hidden-xs hidden-sm">
            <div class="col-sm-8 col-md-9 col-lg-9">
                <ul class="menu list-inline pull-left hidden-xs">
                    <li class="menu__item"><a href="/" class="active-nav">首页</a></li>
                </ul>
            </div>
            {% if not request.user.username %}
                <div class="col-sm-4 col-md-3 col-lg-3 text-right">
                    <ul class="opts list-inline hidden-xs">
                        <li class="menu__item">
                            <button class="btn" onclick="loginOrRegister(this)" value="login">登录</button>
                        </li>
                        <li class="menu__item">
                            <button class="btn" onclick="loginOrRegister(this)" value="register">注册</button>
                        </li>
                    </ul>
                </div>
            {% else %}
                <div class="col-sm-4 col-md-3 col-lg-3 text-right">
                    <ul class="opts list-inline hidden-xs">
                        <li class="menu__item"><a href="{% url 'Rehabilitation:messages' %}">消息<span
                                class="has-unread__count">1</span></a>
                        </li>
                        <li class="opts__item user dropdown hoverDropdown ml0">
                            <a class="avatar-* dropdownBtn user-avatar" data-toggle="dropdown"
                               style="background-image: url('{% fixPath request.user.avatar %}')"
                               href="{% url 'Rehabilitation:userProfile' request.user.username %}"></a>
                        </li>
                        <li class="menu__item"><a
                                href="{% url 'Rehabilitation:logout' %}?next={{ request.path }}">登出</a></li>
                    </ul>
                </div>
            {% endif %}
        </div>
    </nav>
</div>


{% block body %}

{% endblock %}

<div class="sfmodal modal" id="register" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true"
     style="display: none;">
    <div class="modal-dialog ">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true" onclick="closePanel(this)">×</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title">注册</h4></div>
            <div class="modal-body">
                <div class="sfModal-content">
                    <div class="row bg-white login-modal">
                        <div class="col-md-12 login-wrap">
                            <div class="form-group">
                                <label for="username" class="control-label">用户名</label>
                                <input type="text" class="form-control" id="username" tabindex="1" required=""
                                       placeholder="请输入用户名" onblur="checkUsername(this)">
                                <span class="help-block err" style="display: none">用户名已存在</span>
                            </div>
                            <div class="form-group">
                                <label for="password" class="control-label">密码</label>
                                <input type="password" class="form-control" required=""
                                       id="pw1"
                                       placeholder="不少于 6 位的密码">
                            </div>
                            <div class="form-group">
                                <label for="password" class="control-label">再次输入密码</label>
                                <input type="password" class="form-control" required="" id="pw2"
                                       placeholder="不少于 6 位的密码" onblur="validate()">
                                <span class="help-block err" style="display: none">两次密码不一致</span>
                            </div>
                            <div class="form-group clearfix">
                                <button type="button" class="btn-block btn btn-primary pl20 pr20 pull-right"
                                        post_to="{% url 'Rehabilitation:register' %}"
                                        onclick="register(this)">
                                    注册
                                </button>
                            </div>
                            <div class="form-group clearfix">
                                <button class="btn-block btn pl20 pr20 pull-right"
                                        onclick="loginOrRegister(this)" value="login">
                                    已有账号登录
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer hidden"></div>
        </div>
    </div>
</div>

<div class="sfmodal modal in" id="login" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true"
     style="display: none;">
    <div class="modal-dialog ">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true" onclick="closePanel(this)">×</span>
                </button>
                <h4 class="modal-title">登录</h4></div>
            <div class="modal-body">
                <div class="sfModal-content">
                    <div class="row bg-white login-modal">
                        <div class="col-md-12 login-wrap">
                            <span class="help-block err" style="display: none">用户名或密码错误</span>
                            <div class="form-group">
                                <label for="username" class="control-label">用户名</label>
                                <input type="text" class="form-control" name="username" required=""
                                       placeholder="请输入用户名">
                            </div>
                            <div class="form-group">
                                <label class="control-label">密码</label>
                                <input type="password" class="form-control" name="password" required=""
                                       placeholder="请输入密码">
                            </div>
                            <div class="form-group clearfix">
                                <button type="button" class="btn-block btn btn-primary pull-right pl20 pr20"
                                        post_to='{% url 'Rehabilitation:login' %}' next='{{ request.path }}'
                                        onclick="login(this)">
                                    登录
                                </button>
                            </div>
                            <div class="form-group clearfix">
                                <button class="btn-block btn  pl20 pr20 pull-right"
                                        onclick="loginOrRegister(this)" value="register">
                                    注册新账号
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer hidden"></div>
        </div>
    </div>
</div>

<footer id="footer">
    <div class="container">
        <div class="copyright">
            Copyright © 2019-2020<br>
        </div>
    </div>
</footer>

</body>
</html>

templates/Rehabilitation/conversation.html
{% extends 'Rehabilitation/base.html' %}

{% load mytags %}

{% block title %}血友阳光{% endblock %}

{% block static %}
    <script type="text/javascript" src="/static/js/reconnecting-websocket.js"></script>
{% endblock %}

{% block body %}
    <div class="container pt30">
        <div class="row">
            <div class="col-xs-12 col-md-9 main">
                <div class="clearfix mt15">
                    <a href="{% url 'Rehabilitation:messages' %}" class="pull-left btn btn-default btn-xs">← 返回列表</a>
                    <a href="{% url 'Rehabilitation:shieldUser' convId %}"
                       class="pull-right btn btn-default btn-xs ml10">屏蔽用户</a>
                    <a href="{% url 'Rehabilitation:deleteConversation' %}?conv_id={{ convId }}"
                       class="pull-right btn btn-default btn-xs ml10">删除会话</a>
                    {#                    <button id="blockUser"#}
                    {#                            class="pull-right btn btn-default btn-xs ml10">屏蔽用户#}
                    {#                    </button>#}
                    {#                    <button id="delInbox"#}
                    {#                            class="pull-right btn btn-default btn-xs">删除对话#}
                    {#                    </button>#}
                </div>

                <div class="stream-list border-top mt15">
                    <div class="mt15 mr10 ">
                        <div class="media-left pull-left ml10">
                            <a href="/static/img/人工智能.png"></a>
                        </div>
                        <form class="mt15 mb15 messageForm clearfix mr10">
                            <p class="mb7"><strong>发私信给 <a target="_blank"
                                                           href="{% url 'Rehabilitation:userProfile' another_user.username %}">{{ another_user.nickname }}</a>：</strong>
                            </p>
                            {#                            <input id="messageReceiver" type="hidden" name="receiver" value="1030000021849140">#}
                            <textarea class="form-control" id="messageMessage"
                                      placeholder="仅支持纯文本，不超过 1024 字"></textarea>
                            <button class="btn btn-primary pull-right mt15" id="sendMsg" conv_id="{{ convId }}"
                                    onclick="sendMessage(this)" post_to= {% url 'Rehabilitation:sendMessage' %}>
                                发送
                            </button>
                        </form>
                        <hr class="mt15 mb0">
                    </div>
                    <div id="messages">
                        {% for conv in conv_list %}
                            <section class="stream-list__item  mr10">
                                <div class="media">
                                    <div class="media-left pull-left">
                                        <a href="{% url 'Rehabilitation:userProfile' conv.send_user.username %}"><img
                                                class="avatar-40"
                                                src="{% fixPath conv.send_user.avatar %}"></a>
                                    </div>
                                    <div class="media-body">
                                        <div>
                                            <a href="{% url 'Rehabilitation:userProfile' conv.send_user.username %}"><strong>{{ conv.send_user.nickname }}</strong></a>
                                            <span class="text-muted pull-right">{{ conv.send_date }}</span>
                                        </div>
                                        <div class="clearfix">
                                            <p class="col-xs-11 pull-left text-muted mb0 fmt p-l-0">
                                                {{ conv.msg_detail }}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </section>
                        {% endfor %}
                    </div>

                </div><!-- /.stream-list -->

            </div><!-- /.main -->
            <div class="col-md-3"></div>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            const ws_scheme = window.location.protocol === "https:" ? "wss" : "ws";
            const ws_path = ws_scheme + "://" + window.location.host + "/" + "ws" + "/" + "abc" + "{{ current_user.id }}" + "/";
            const ws = new ReconnectingWebSocket(ws_path);
            ws.onmessage = function (event) {
                const data = JSON.parse(event.data);
                console.log(data['massage'])
                $('#messages').prepend(data['massage'])
            }
        })
    </script>
{% endblock %}

templates/Rehabilitation/index.html
{% extends 'Rehabilitation/base.html' %}

{% load mytags %}

{% block title %}血友阳光{% endblock %}

{% block body %}
    <div class="wrapper">
        <div class="container mt30">
            <div class="row">
                <div class="col-md-2 left">
                    {#                    <div class="router-box">#}
                    {#                        <a class="router-box-item active" href="https://segmentfault.com/">#}
                    {#                            <i class="fa fa-newspaper-o" aria-hidden="true"></i>#}
                    {#                            <span class="name">为你推荐</span>#}
                    {#                        </a>#}
                    {#                        <a class="router-box-item " href="https://segmentfault.com/hottest">#}
                    {#                            <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>#}
                    {#                            <span class="name">近期热门</span>#}
                    {#                        </a>#}
                    {#                        <a class="router-box-item " href="https://segmentfault.com/newest">#}
                    {#                            <i class="fa fa-globe" aria-hidden="true"></i>#}
                    {#                            <span class="name">最新内容</span>#}
                    {#                        </a>#}
                    {#                    </div>#}
                </div>

                <div class="col-md-7 middle">
                    <div class="feed-option">
                        <h5>为你推荐</h5>
                    </div>

                    <div class="news-list">
                        {% for article in article_list %}
                            <div class="news-item stream__item clearfix mt15 feed-option ">
                                <div class="news__item-info clearfix">
                                    <a href="" class="news-img"
                                       style=""></a>
                                    <a target="_blank" href="{% url 'Rehabilitation:article' article.id %}">
                                        <div class="mb5 mt5">
                                            <h4 class="">{{ article.title }}</h4>
                                        </div>
                                        <div class="article-excerpt">
                                            {{ article.brief }}
                                        </div>
                                    </a>
                                    <div class="news__item-meta">
                                        <span class="votes-word">赞</span>
                                        <span class="dot ">*</span>
                                        <span class="votes-num  ">{% likeCount article %}</span>
                                        <span class="pr20 votes-operation "></span>
                                        <span class="author pr20">
                                    <a href="{% url 'Rehabilitation:userProfile' article.author.username %}">{{ article.author.nickname }}</a>
                                    <span class="dot">·</span>
                                    {{ article.pub_date }}
                                </span>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                </div>

                {#                <div class="col-md-3 right">#}
                {#                    <div class="activity-recommend mb30">#}
                {#                        <a href="https://segmentfault.com/events" class="more-btn pull-right">更多</a>#}
                {#                        <div class="activity-title">活动推荐</div>#}
                {#                        <div class="activity-recommend-area">#}
                {#                            <a class="activity-recommend-item" href="https://segmentfault.com/e/1160000021828190">#}
                {#                                <div class="activity-date pull-left">#}
                {#                                    <div class="activity-date-wrapper">#}
                {#                                        <div class="activity-date-up">MAR</div>#}
                {#                                        <div class="activity-date-down">17</div>#}
                {#                                    </div>#}
                {#                                </div>#}
                {#                                <div class="activity-detail">#}
                {#                                    <div class="activity-detail-title">高校AI小程序战疫大赛</div>#}
                {#                                    <span class="activity-detail-base">北京</span><span class="dot">·</span>03-17&nbsp;&nbsp;周二<span#}
                {#                                        class="dot">·</span><span#}
                {#                                        class="activity-state">报名中</span>#}
                {#                                </div>#}
                {#                            </a>#}
                {#                        </div>#}
                {#                    </div>#}
                {#                </div>#}
            </div>
        </div>
    </div>
{% endblock %}

templates/Rehabilitation/simple_message.html
{% load mytags %}
<section class="stream-list__item  mr10">
    <div class="media">
        <div class="media-left pull-left">
            <a href=""><img class="avatar-40"
                            src="{% fixPath current_user.avatar %}"></a>
        </div>
        <div class="media-body">
            <div>
                <a href=""><strong>{{ message_detail.send_user.nickname }}</strong></a>
                <span class="text-muted pull-right">{{ message_detail.send_date }}</span>
            </div>
            <div class="clearfix">
                <p class="col-xs-11 pull-left text-muted mb0 fmt p-l-0">
                    {{ message_detail.msg_detail }}
                </p>
            </div>
        </div>
    </div>
</section>